import { Geist, Geist_Mono, Jersey_20 } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const jersey20 = Jersey_20({
  variable: '--font-jersey-20',
  subsets: ["latin"],
  weight: ['400']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${jersey20.variable} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
